contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dnangs channel"
    url: https://nfcore.slack.com/channels/dnangs
    about: Discussion about the nf-core/dnangs pipeline
